= Factory Pattern Kod Satırı Açıklaması

[source,C#]
----
//Transportation.cs Sınıfı

using System;
using System.Collections.Generic;
using System.Text; // <1>

namespace YazılımTasarınKalıplarıFactoryPattern // <2>
{
    public interface Transportation // <3>
    {
         void TransportProducts();
    }

    public class Truck : Transportation // <4>
    {
        public void TransportProducts()
        {
            Console.WriteLine("The products have been posted by Truck"); //Override
        }
    }

    public class Ship : Transportation // <5>
    {
        public void TransportProducts()
        {
            Console.WriteLine("The products have been posted by Ship"); //Override
        }
    }

    public class Plane : Transportation //<6>
    {
        public void TransportProducts()
        {
            Console.WriteLine("The products have been posted by Plane"); //Override
        }
    }
}

// TransportationFactory.cs Sınıfı

using System;
using System.Collections.Generic;
using System.Text;

namespace YazılımTasarınKalıplarıFactoryPattern
{
    public class TransportationFactory
    {
        public Transportation getVehicle(String transportationType) // <7>
        {
            if (transportationType == null) return null;
            if (transportationType.Equals("Truck", StringComparison.InvariantCultureIgnoreCase)) // <8>
            {
                return new Truck();
            }
            else if (transportationType.Equals("Ship", StringComparison.InvariantCultureIgnoreCase)) // <9>
            {
                return new Ship();
            }
            else if (transportationType.Equals("Plane", StringComparison.InvariantCultureIgnoreCase)) // <10>
            {
                return new Plane();
            }
            return null;
        }
    }
   
}

// Program.cs Sınıfı
using System;

namespace YazılımTasarınKalıplarıFactoryPattern
{
    class Program
    {
        public static void Main(string[] args)
        {
            TransportationFactory transportationFactory = new TransportationFactory(); // <11> 

            Transportation transportation1 = transportationFactory.getVehicle("Ship");
            transportation1.TransportProducts();

            Transportation transportation2 = transportationFactory.getVehicle("Plane");
            transportation2.TransportProducts();

            Transportation transportation3 = transportationFactory.getVehicle("Truck");
            transportation3.TransportProducts();

        }
    }
}

----
<1> Kütüphane Erişim

<2> Namespace İsmi

<3> Interface Tanımlaması

<4> Truck sınıfının Transportation interface ' den kalıtılması ve içerisinde TransportProducts() methodunun override edilmesi.

<5> Ship sınıfının Transportation interface ' den kalıtılması ve içerisinde TransportProducts() methodunun override edilmesi.

<6> Plane sınıfının Transportation interface ' den kalıtılması ve içerisinde TransportProducts() methodunun override edilmesi.

<7> GetVehicle adlı Methodun Oluşturulması

<8> Truck Transportation işlemi Seçildiginde Truck () methodunun döndürülmesi.

<9> Ship Transportation işlemi Seçildiginde Truck () methodunun döndürülmesi.


<10> Plane Transportation işlemi Seçildiginde Truck () methodunun döndürülmesi.

<11> TransportationFactory sınıfı tipinde transportationFactory nesnesinin oluşturulması.
