= Singleton Pattern Kod Satırı Açıklaması

[source,C#]
----

-----SingletonMainProgram.cs Sınıfı -----

using System; // <1> 

namespace SingletonPattern // <2>
{
    class SingletonMainProgram // <3>
    {
        public static void Main(string[] args)
        {
            Singleton singleton1 = Singleton.CreateInstance() // <4>
            Singleton singleton2 = Singleton.CreateInstance(); // <5>

            if(singleton1 == singleton2) // <6>
            {
                Console.WriteLine("Objects are using the same instance"); // <7>
            }
            else
            {
                Console.WriteLine("Objects are not using the same instance"); // <8>
            }
        }
    }
}

-----Singleton.cs Sınıfı-----
using System;
using System.Collections.Generic;
using System.Text;

namespace SingletonPattern 
{
    public sealed class Singleton
    {
        private static Singleton instance = null; //<9>
        private Singleton() // <10>
        {

        }

        public static Singleton CreateInstance()
        {
            if (instance == null) // <11>
            {
                instance = new Singleton();// <12>
            }

            return instance; // <13>
        }
    }
}
----
<1> Kütüphane Ekleme

<2> Namespace İsmi

<3> SingletonMainProgram adlı sınıfın kod blogunun başlangıcı

<4> Singleton tipindeki singleton1 nesnesi için Singleton sınıfındaki CreateInstance methoduna başvuru.

<5> Singleton tipindeki singleton2 nesnesi için Singleton sınıfındaki CreateInstance methoduna başvuru.

<6> CreateInstance methodunun gelen instance'a göre singleton örüntüsünün dogru çalışıp çalışmadığının ekrana basılması.

<7> Tek bir instance döndürülerek singleton örüntüsünün temel ilkesinin sağlandığını gösterir.

<8> Singleton örüntüsünün doğru çalışmadığını gösterir.

<9> Singleton tipindeki statik nesnesin tanımlanması ve null degerine eşitlenmesi

<10> Private Constructor Tanımlanması

<11> instance degerinin null olup olmadığı kontrolü

<12> instance oluşturma (Daha önce oluşturulmamış, ilk defa oluşturuluyor anlamı taşır.)

<13> Oluşturulan Instance return edilir.

