= Singleton Thread Safe Kod Parçası Açıklaması

[source,C#]
----

//SingletonMainProgram.cs Sınıfı

using System;
using System.Threading.Tasks; // <1>

namespace Yazılım_Tasarım_Kalıpları // <2>
{
    class SingletonMainProgram // <3>
    {
        static void Main(string[] args)
        {
            Parallel.Invoke( // <4>
                () => PrintAliceMessage(),
                () => PrintBobMessage()
                );
        }
        private static void PrintAliceMessage() // <5>
        {
            SingletonObject aliceMessage =  SingletonObject.CreateInstance; // <6>
            Console.WriteLine("Authentication requested from Alice");
        }
        private static void PrintBobMessage() // <7>
        {
            SingletonObject bobMessage =  SingletonObject.CreateInstance;// <8>
            Console.WriteLine("Authentication responded from Bob");
        }
    }
}

//SingletonObject.cs Sınıfı

using System;
using System.Collections.Generic;
using System.Text;

namespace Yazılım_Tasarım_Kalıpları
{
    public sealed class SingletonObject
    {
        private static SingletonObject singletonInstance = null; // <9> 
        private static readonly object Instancelock = new object(); // <10>
        private SingletonObject() // <11>
        {

        }
        public static SingletonObject CreateInstance
        {
            get
            {
                if (singletonInstance == null) // <12>
                {
                    lock (Instancelock) // <13>
                    {
                        if (singletonInstance == null) // <14>
                        {
                            singletonInstance = new SingletonObject(); // <15>
                        }
                    }
                }
                return singletonInstance; // <16>
            }
        }
    }
}
----
<1> Kütüphane Erişimi

<2> Namespace İsmi
<3> SingletonMainProgram sınıfının kod blogunun başlangıcı.
<4> Thread yapısının kurulması. 2 Farkılı methoda görev atamasının yapılması.

<5> PrintAliceMessage () metodunun kurulması.
<6> SingletonObject tipindeki aliceMessage nesnesinin CreateInstance methodundan talep edilmesi.

<7> PrintAliceMessage () metodunun Oluşturulması.

<8> SingletonObject tipindeki bobMessage nesnesinin CreateInstance methodundan talep edilmesi.

<9> SingletonObject tipindeki instance'ın tanımlanması.

<10> Lock (Kitleme) işlemi için gerekli Instancelock nesnesinin oluşturulması.

<11> Private Constructor'ın oluşturulması.

<12> Double Checking işlemi (Singletoninstance deger kontrolü).

<13> Paylaşılmış kaynağın thread ler için kilitlenmesi.

<14> Instance'ın önceden oluşturulup oluşturulmadığının kontrolü.

<15> Instance'ın ilk defa oluşturulduğu durumdaki instance oluşturma kod satırı.

<16> Oluşturulmuş instance'ın geri döndürülüşü.


